version: '2'
services:
    medicalrec-app:
        image: medicalrec
        external_links:
            - medicalrec-mysql:mysql
        environment:
            - SPRING_PROFILES_ACTIVE=prod
            - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/medicalrec?useUnicode=true&characterEncoding=utf8&useSSL=false
        ports:
            - 8080:8080
    medicalrec-mysql:
        extends:
            file: mysql.yml
            service: medicalrec-mysql
